# Generated by Django 6.0.4 on 2026-05-19 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0013_add_tipos_escala_to_militar'),
    ]

    operations = [
        migrations.CreateModel(
            name='LancamentoManualQuadrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(help_text='Ano de referência do lançamento')),
                ('tipo', models.CharField(choices=[('lastro', 'Lastro'), ('atestado', 'Atestado'), ('ferias', 'Férias'), ('dispensa', 'Dispensa'), ('particular', 'Particular'), ('chefe', 'Serviço de Chefe'), ('outro', 'Outro')], default='lastro', max_length=20, verbose_name='Tipo')),
                ('label', models.CharField(help_text="Texto exibido na célula da matriz — ex: 'Lastro', 'Férias jan/25', 'Atestado'", max_length=100, verbose_name='Descrição (exibida na matriz)')),
                ('quantidade', models.PositiveIntegerField(default=1, help_text='Quantos serviços este lançamento representa (ex: Lastro +3 → quantidade=3)', verbose_name='Quantidade')),
                ('observacao', models.TextField(blank=True, help_text='Detalhe opcional (não exibido na matriz)', verbose_name='Observação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('militar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_manuais', to='escalas.militar')),
                ('tipo_escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_manuais', to='escalas.tipoescala')),
                ('tipo_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_manuais', to='escalas.tiposervico')),
            ],
            options={
                'verbose_name': 'Lançamento Manual de Quadrinho',
                'verbose_name_plural': 'Lançamentos Manuais de Quadrinho',
                'db_table': 'lancamento_manual_quadrinho',
                'ordering': ['ano', 'militar__nome_guerra', 'data_criacao'],
                'indexes': [models.Index(fields=['militar', 'tipo_escala', 'tipo_servico', 'ano'], name='lancamento__militar_061b2d_idx')],
            },
        ),
    ]
