# Generated by Django 6.0.4 on 2026-06-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0018_aprovacao_troca_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='militar',
            name='nota',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Nota do curso de promoção ao posto atual (ex: 8,75). Critério de desempate de antiguidade: nota maior = mais antigo.', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='escala',
            name='status',
            field=models.CharField(choices=[('previsao', 'Previsão'), ('publicada', 'Escala (Oficial)')], default='previsao', max_length=20),
        ),
        migrations.AlterField(
            model_name='trocaservico',
            name='aprovada_militar_entra',
            field=models.BooleanField(blank=True, default=None, help_text='Militar que entra aprovou a troca (None=pendente, True=aceito, False=recusado)', null=True),
        ),
        migrations.AlterField(
            model_name='trocaservico',
            name='aprovada_militar_entra_2',
            field=models.BooleanField(blank=True, default=None, help_text='Segundo militar que entra aprovou a troca (None=pendente)', null=True),
        ),
        migrations.AlterField(
            model_name='trocaservico',
            name='aprovada_militar_sai',
            field=models.BooleanField(default=False, help_text='Militar que sai aprovou a troca (True=aprovado, False=recusado)'),
        ),
        migrations.AlterField(
            model_name='trocaservico',
            name='aprovada_militar_sai_2',
            field=models.BooleanField(blank=True, default=None, help_text='Segundo militar que sai aprovou a troca (None=pendente)', null=True),
        ),
    ]
