# Generated by Django 6.0.4 on 2026-06-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0019_add_nota_to_militar'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoescala',
            name='permitir_quebrar_folga',
            field=models.BooleanField(default=True, help_text='Se ativado, quando todos os militares estiverem em folga, o motor escala o de menor count (com alerta ⚠ e forcar_escala=True). Se desativado, o dia fica sem cobertura e gera alerta crítico 🚨.', verbose_name='Permitir quebrar folga em último caso'),
        ),
    ]
