# Generated by Django 6.0.4 on 2026-06-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0020_add_permitir_quebrar_folga'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoindisponibilidade',
            name='gera_bloqueio_pos',
            field=models.BooleanField(default=False, help_text='Se ativado, bloqueia serviços dentro do período de folga mínima APÓS o retorno deste tipo de indisponibilidade. Recomendado apenas para Férias.', verbose_name='Gera bloqueio pós-período'),
        ),
        migrations.AddField(
            model_name='tipoindisponibilidade',
            name='gera_bloqueio_pre',
            field=models.BooleanField(default=False, help_text='Se ativado, bloqueia serviços que terminariam dentro do período de folga mínima ANTES do início deste tipo de indisponibilidade. Recomendado apenas para Férias.', verbose_name='Gera bloqueio pré-período'),
        ),
    ]
