# """
# Django settings for core project.

# Generated by 'django-admin startproject' using Django 5.2.1.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.2/ref/settings/
# """
# import os
# from pathlib import Path

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-tv=yz++fhm@$vipya_&q0#5uh*8bp0-pk%!(a2jxa8yzy4ck#9'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = ['*']


# CSRF_TRUSTED_ORIGINS = ['http://10.100.0.34', 'http://localhost', 'http://demeter.xxxx.internet',  'https://escala.xxxx.internet']

# AUTH_USER_MODEL = 'escalas.UsuarioCustomizado'

# LOGIN_URL = '/login/'
# LOGIN_REDIRECT_URL = '/'
# LOGOUT_REDIRECT_URL = '/login/'


# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'escalas',
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'core.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR / 'templates'],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#                 'escalas.context_processors.om_context',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'core.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# # Password validation
# # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # internettionalization
# # https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'pt-br'

# TIME_ZONE = 'America/Sao_Paulo'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = '/static/'
# STATIC_ROOT = BASE_DIR / 'staticfiles'
# STATICFILES_DIRS = [BASE_DIR / 'static']

# # Uploads (logos das OMs etc.)
# MEDIA_URL = 'media/'
# MEDIA_ROOT = BASE_DIR / 'media'

# # Default primary key field type
# # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# # ===========================================================================
# # AUTENTICAÇÃO LDAP / ACTIVE DIRECTORY
# # ===========================================================================
# # Para habilitar o login via LDAP:
# #   1. Instale: pip install django-auth-ldap
# #   2. Descomente as configurações abaixo e ajuste os valores
# #   3. O backend CustomLDAPBackend (core/backend.py) garante que apenas
# #      usuários previamente cadastrados no sistema consigam autenticar via LDAP
# #
# # Fluxo de autenticação:
# #   - Login → CustomLDAPBackend verifica se username existe localmente
# #   - Se existir: autentica via LDAP (valida senha no AD)
# #   - Se não existir: ModelBackend tenta senha local (fallback)
# # ===========================================================================

# import ldap
# from django_auth_ldap.config import LDAPSearch


# FORMATTERS = (
#     {
#         "verbose": {
#             "format": "{levelname} {asctime:s} {threadName} {thread:d} {module} {filename} {lineno:d} {name} {funcName} {process:d} {message}",
#             "style": "{",
#         },
#         "simple": {
#             "format": "{levelname} {asctime:s} {module} {filename} {lineno:d} {funcName} {message}",
#             "style": "{",
#         },
#     },
# )


# HANDLERS = {
#     "console_handler": {
#         "class": "logging.StreamHandler",
#         "formatter": "simple",
#     },
#     "my_handler": {
#         "class": "logging.handlers.RotatingFileHandler",
#         "filename": f"{BASE_DIR}/logs/blogthedata.log",
#         "mode": "a",
#         "encoding": "utf-8",
#         "formatter": "simple",
#         "backupCount": 5,
#         "maxBytes": 1024 * 1024 * 5,  # 5 MB
#     },
#     "my_handler_detailed": {
#         "class": "logging.handlers.RotatingFileHandler",
#         "filename": f"{BASE_DIR}/logs/django.log",
#         "mode": "a",
#         "formatter": "verbose",
#         "backupCount": 5,
#         "maxBytes": 1024 * 1024 * 5,  # 5 MB
#     },
# }


#     # DEBUG: Informações de sistema de baixo nível para propósitos de depuração
#     # INFO: Informações gerais de sistema
#     # WARNING: Informações descrevendo a ocorrência de um pequeno problema
#     # ERROR: Informações descrevendo a ocorrência de um problema grande.
#     # CRITICAL: Informações descrevendo a ocorrência de um problema crítico.

# LOGGERS = (
#     {
#         "django": {
#             "handlers": ["console_handler", "my_handler_detailed"],
#             "level": "ERROR",
#             "propagate": False,
#         },
#         "django.request": {
#             "handlers": ["my_handler"],
#             "level": "WARNING",
#             "propagate": False,
#         },
#     },
# )


# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "formatters": FORMATTERS[0],
#     "handlers": HANDLERS,
#     "loggers": LOGGERS[0],
# }

# from django_auth_ldap.config import *
# from django_auth_ldap.config import LDAPSearch

# AUTH_LDAP_SERVER_URI = "ldap://10.100.0.0:389"
# AUTH_LDAP_BIND_DN = "cn=django,ou=xxxx,dc=xxxx,dc=internet"
# AUTH_LDAP_BIND_PASSWORD = "xxxxxyyy"

# AUTH_LDAP_USER_SEARCH = LDAPSearch(
# #            "ou=xxxx,dc=xxxx,dc=internet", ldap.SCOPE_SUBTREE, "(uid=%(user)s)"
#             "ou=xxxx,dc=xxxx,dc=internet", ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)"
#             )

# AUTH_LDAP_USER_ATTR_MAP = {
#             "username": "sAMAccountName",
# #            "username": "uid",
#                "first_name": "name",
#                     "last_name": "physicalDeliveryOfficeName",
# 			#"posto_nome": "cn",
# #                        "email": "mail",
# }


# # AUTHENTICATION_BACKENDS = [
# #             'django_auth_ldap.backend.LDAPBackend',
# #             'django.contrib.auth.backends.ModelBackend',
# # ]

# AUTHENTICATION_BACKENDS = [
#             'core.backend.CustomLDAPBackend',
#                 'django.contrib.auth.backends.ModelBackend',
# ]


# # Configurações opcionais do django-auth-ldap:
# AUTH_LDAP_ALWAYS_UPDATE_USER = True   # Sincroniza first_name/last_name/email a cada login
# AUTH_LDAP_CACHE_TIMEOUT = 3600        # Cache de grupo em segundos


import os
from pathlib import Path

# =============================================================================
# PATHS
# =============================================================================

BASE_DIR = Path(__file__).resolve().parent.parent

LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

# =============================================================================
# SECURITY
# =============================================================================

SECRET_KEY = "django-insecure-tv=yz++fhm@$vipya_&q0#5uh*8bp0-pk%!(a2jxa8yzy4ck#9"

DEBUG = True

ALLOWED_HOSTS = [
    "*",
]

CSRF_TRUSTED_ORIGINS = [
    "http://10.100.0.0",
    "http://localhost",
    "http://demeter.xxxx.internet",
    "https://escala.xxxx.internet",
    "https://*.replit.dev",
    "https://*.replit.app",
    "https://*.repl.co",
    "https://*.kirk.replit.dev",
    "https://*.picard.replit.dev",
]

# =============================================================================
# AUTH
# =============================================================================

AUTH_USER_MODEL = "escalas.UsuarioCustomizado"

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"

# =============================================================================
# APPLICATIONS
# =============================================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "escalas",
]

# =============================================================================
# MIDDLEWARE
# =============================================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# =============================================================================
# URLS / TEMPLATES
# =============================================================================

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "escalas.context_processors.om_context",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"

# =============================================================================
# DATABASE
# =============================================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# =============================================================================
# PASSWORD VALIDATION
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# =============================================================================
# internetTIONALIZATION
# =============================================================================

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True
USE_TZ = True

# =============================================================================
# STATIC FILES
# =============================================================================

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# =============================================================================
# MEDIA FILES
# =============================================================================

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"

# =============================================================================
# DEFAULT PK
# =============================================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =============================================================================
# LOGGING
# =============================================================================

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "verbose": {
            "format": (
                "{levelname} "
                "{asctime} "
                "{threadName} "
                "{module} "
                "{filename} "
                "{lineno} "
                "{funcName} "
                "{message}"
            ),
            "style": "{",
        },

        "simple": {
            "format": (
                "{levelname} "
                "{asctime} "
                "{module} "
                "{lineno} "
                "{message}"
            ),
            "style": "{",
        },
    },

    "handlers": {

        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },

        "django_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "django.log",
            "formatter": "verbose",
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "encoding": "utf-8",
        },

        "request_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "requests.log",
            "formatter": "simple",
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "encoding": "utf-8",
        },
    },

    "loggers": {

        "django": {
            "handlers": ["console", "django_file"],
            "level": "DEBUG",
            "propagate": False,
        },

        "django.request": {
            "handlers": ["request_file"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}

# =============================================================================
# LDAP / ACTIVE DIRECTORY
# =============================================================================

# from django_auth_ldap.config import *
# from django_auth_ldap.config import LDAPSearch

# AUTH_LDAP_SERVER_URI = "ldap://10.100.0.1:389"
# AUTH_LDAP_BIND_DN = "cn=django,ou=xxxx,dc=xxxx,dc=internet"
# AUTH_LDAP_BIND_PASSWORD = "XXXXXX"

# AUTH_LDAP_USER_SEARCH = LDAPSearch(
# #            "ou=xxxx,dc=xxxx,dc=internet", ldap.SCOPE_SUBTREE, "(uid=%(user)s)"
#             "ou=xxxx,dc=xxxx,dc=internet", ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)"
#             )

# AUTH_LDAP_USER_ATTR_MAP = {
#             "username": "sAMAccountName",
# #            "username": "uid",
#                "first_name": "name",
#                     "last_name": "physicalDeliveryOfficeName",
# 			#"posto_nome": "cn",
# #                        "email": "mail",
# }


# # AUTHENTICATION_BACKENDS = [
# #             'django_auth_ldap.backend.LDAPBackend',
# #             'django.contrib.auth.backends.ModelBackend',
# # ]

# AUTHENTICATION_BACKENDS = [
#             'core.backend.CustomLDAPBackend',
#                 'django.contrib.auth.backends.ModelBackend',
# ]


# AUTH_LDAP_ALWAYS_UPDATE_USER = True

# AUTH_LDAP_CACHE_TIMEOUT = 3600

# =============================================================================
# SECURITY OPTIONS (opcional)
# =============================================================================

SESSION_COOKIE_HTTPONLY = True

CSRF_COOKIE_HTTPONLY = False

X_FRAME_OPTIONS = "DENY"

SECURE_BROWSER_XSS_FILTER = True

SECURE_CONTENT_TYPE_NOSNIFF = True

# =============================================================================
# DEBUG TOOLBAR / DEV ONLY (opcional)
# =============================================================================

if DEBUG:
    internetL_IPS = [
        "127.0.0.1",
    ]
